package cn.generator.mapper;

import cn.generator.pojo.MovieClass;

public interface MovieClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_class
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Short cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_class
     *
     * @mbggenerated
     */
    int insert(MovieClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_class
     *
     * @mbggenerated
     */
    int insertSelective(MovieClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_class
     *
     * @mbggenerated
     */
    MovieClass selectByPrimaryKey(Short cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_class
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MovieClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_class
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MovieClass record);
}