package cn.generator.mapper;

import cn.generator.pojo.Movie;
import cn.generator.pojo.MovieWithBLOBs;

import java.util.List;

public interface MovieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer mId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie
     *
     * @mbggenerated
     */
    int insert(MovieWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie
     *
     * @mbggenerated
     */
    int insertSelective(MovieWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie
     *
     * @mbggenerated
     */
    MovieWithBLOBs selectByPrimaryKey(Integer mId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MovieWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(MovieWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Movie record);

    /**
     * 通过playurl查询是否存在相同视频
     */
    int selectplayurl(String mPlayurl, String mClass);

    /**
     * 通过playurl查询视频
     */
    List<MovieWithBLOBs> selectplayorderbyurl(String mPlayurl);



    //     通过class找相关movie信息
    List<MovieWithBLOBs> selectMoiveOrderByClass(String mClass);

    //在play播放页中获取推荐movie

   List<MovieWithBLOBs> selectRandByClass(String mClass);


    //     加载瀑布流更多
    List<MovieWithBLOBs> selectMoiveOrderByClassMore(String mClass,int start,int end);
}