package cn.generator.mapper;

import cn.generator.pojo.OodManager;

public interface OodManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ood_manager
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Short mId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ood_manager
     *
     * @mbggenerated
     */
    int insert(OodManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ood_manager
     *
     * @mbggenerated
     */
    int insertSelective(OodManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ood_manager
     *
     * @mbggenerated
     */
    OodManager selectByPrimaryKey(Short mId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ood_manager
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OodManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ood_manager
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OodManager record);
}