package cn.generator.mapper;

import cn.generator.pojo.OodUser;
import cn.generator.pojo.OodUserWithBLOBs;
import cn.generator.pojo.UserWithRole;

import java.util.List;
import java.util.Set;

public interface OodUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ood_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer uId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ood_user
     *
     * @mbggenerated
     */
    int insert(OodUserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ood_user
     *
     * @mbggenerated
     */
    int insertSelective(OodUserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ood_user
     *
     * @mbggenerated
     */
    OodUserWithBLOBs selectByPrimaryKey(Integer uId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ood_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OodUserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ood_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(OodUserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ood_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OodUser record);
//    检验用户名是否存在

    int selectUserNameIsExsit(String name);

//   检验用户名和密码是否一致
    int selectUserCheckAllMessage(String name, String passworld);

    List<UserWithRole> FindUserAdmin();//查询普通管理员


    Set<String> findRoles(String username);

    String findPermissions(String username);

    OodUser findUserByUsername(String username);



}