package cn.generator.pojo;

public class MovieWithBLOBs extends Movie {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_content
     *
     * @mbggenerated
     */
    private String mContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_playurl
     *
     * @mbggenerated
     */
    private String mPlayurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_downurl
     *
     * @mbggenerated
     */
    private String mDownurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_content
     *
     * @return the value of movie.m_content
     *
     * @mbggenerated
     */
    public String getmContent() {
        return mContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_content
     *
     * @param mContent the value for movie.m_content
     *
     * @mbggenerated
     */
    public void setmContent(String mContent) {
        this.mContent = mContent == null ? null : mContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_playurl
     *
     * @return the value of movie.m_playurl
     *
     * @mbggenerated
     */
    public String getmPlayurl() {
        return mPlayurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_playurl
     *
     * @param mPlayurl the value for movie.m_playurl
     *
     * @mbggenerated
     */
    public void setmPlayurl(String mPlayurl) {
        this.mPlayurl = mPlayurl == null ? null : mPlayurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_downurl
     *
     * @return the value of movie.m_downurl
     *
     * @mbggenerated
     */
    public String getmDownurl() {
        return mDownurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_downurl
     *
     * @param mDownurl the value for movie.m_downurl
     *
     * @mbggenerated
     */
    public void setmDownurl(String mDownurl) {
        this.mDownurl = mDownurl == null ? null : mDownurl.trim();
    }
}