package cn.generator.pojo;

public class MovieType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_type.t_id
     *
     * @mbggenerated
     */
    private Short tId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_type.t_name
     *
     * @mbggenerated
     */
    private String tName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_type.t_enname
     *
     * @mbggenerated
     */
    private String tEnname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_type.t_pid
     *
     * @mbggenerated
     */
    private Short tPid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_type.t_sort
     *
     * @mbggenerated
     */
    private Short tSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_type.t_hide
     *
     * @mbggenerated
     */
    private Boolean tHide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_type.t_tpl
     *
     * @mbggenerated
     */
    private String tTpl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_type.t_tpl_list
     *
     * @mbggenerated
     */
    private String tTplList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_type.t_tpl_vod
     *
     * @mbggenerated
     */
    private String tTplVod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_type.t_tpl_play
     *
     * @mbggenerated
     */
    private String tTplPlay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_type.t_tpl_down
     *
     * @mbggenerated
     */
    private String tTplDown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_type.t_key
     *
     * @mbggenerated
     */
    private String tKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_type.t_des
     *
     * @mbggenerated
     */
    private String tDes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_type.t_title
     *
     * @mbggenerated
     */
    private String tTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_type.t_union
     *
     * @mbggenerated
     */
    private String tUnion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_type.t_id
     *
     * @return the value of movie_type.t_id
     *
     * @mbggenerated
     */
    public Short gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_type.t_id
     *
     * @param tId the value for movie_type.t_id
     *
     * @mbggenerated
     */
    public void settId(Short tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_type.t_name
     *
     * @return the value of movie_type.t_name
     *
     * @mbggenerated
     */
    public String gettName() {
        return tName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_type.t_name
     *
     * @param tName the value for movie_type.t_name
     *
     * @mbggenerated
     */
    public void settName(String tName) {
        this.tName = tName == null ? null : tName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_type.t_enname
     *
     * @return the value of movie_type.t_enname
     *
     * @mbggenerated
     */
    public String gettEnname() {
        return tEnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_type.t_enname
     *
     * @param tEnname the value for movie_type.t_enname
     *
     * @mbggenerated
     */
    public void settEnname(String tEnname) {
        this.tEnname = tEnname == null ? null : tEnname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_type.t_pid
     *
     * @return the value of movie_type.t_pid
     *
     * @mbggenerated
     */
    public Short gettPid() {
        return tPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_type.t_pid
     *
     * @param tPid the value for movie_type.t_pid
     *
     * @mbggenerated
     */
    public void settPid(Short tPid) {
        this.tPid = tPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_type.t_sort
     *
     * @return the value of movie_type.t_sort
     *
     * @mbggenerated
     */
    public Short gettSort() {
        return tSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_type.t_sort
     *
     * @param tSort the value for movie_type.t_sort
     *
     * @mbggenerated
     */
    public void settSort(Short tSort) {
        this.tSort = tSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_type.t_hide
     *
     * @return the value of movie_type.t_hide
     *
     * @mbggenerated
     */
    public Boolean gettHide() {
        return tHide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_type.t_hide
     *
     * @param tHide the value for movie_type.t_hide
     *
     * @mbggenerated
     */
    public void settHide(Boolean tHide) {
        this.tHide = tHide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_type.t_tpl
     *
     * @return the value of movie_type.t_tpl
     *
     * @mbggenerated
     */
    public String gettTpl() {
        return tTpl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_type.t_tpl
     *
     * @param tTpl the value for movie_type.t_tpl
     *
     * @mbggenerated
     */
    public void settTpl(String tTpl) {
        this.tTpl = tTpl == null ? null : tTpl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_type.t_tpl_list
     *
     * @return the value of movie_type.t_tpl_list
     *
     * @mbggenerated
     */
    public String gettTplList() {
        return tTplList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_type.t_tpl_list
     *
     * @param tTplList the value for movie_type.t_tpl_list
     *
     * @mbggenerated
     */
    public void settTplList(String tTplList) {
        this.tTplList = tTplList == null ? null : tTplList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_type.t_tpl_vod
     *
     * @return the value of movie_type.t_tpl_vod
     *
     * @mbggenerated
     */
    public String gettTplVod() {
        return tTplVod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_type.t_tpl_vod
     *
     * @param tTplVod the value for movie_type.t_tpl_vod
     *
     * @mbggenerated
     */
    public void settTplVod(String tTplVod) {
        this.tTplVod = tTplVod == null ? null : tTplVod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_type.t_tpl_play
     *
     * @return the value of movie_type.t_tpl_play
     *
     * @mbggenerated
     */
    public String gettTplPlay() {
        return tTplPlay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_type.t_tpl_play
     *
     * @param tTplPlay the value for movie_type.t_tpl_play
     *
     * @mbggenerated
     */
    public void settTplPlay(String tTplPlay) {
        this.tTplPlay = tTplPlay == null ? null : tTplPlay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_type.t_tpl_down
     *
     * @return the value of movie_type.t_tpl_down
     *
     * @mbggenerated
     */
    public String gettTplDown() {
        return tTplDown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_type.t_tpl_down
     *
     * @param tTplDown the value for movie_type.t_tpl_down
     *
     * @mbggenerated
     */
    public void settTplDown(String tTplDown) {
        this.tTplDown = tTplDown == null ? null : tTplDown.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_type.t_key
     *
     * @return the value of movie_type.t_key
     *
     * @mbggenerated
     */
    public String gettKey() {
        return tKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_type.t_key
     *
     * @param tKey the value for movie_type.t_key
     *
     * @mbggenerated
     */
    public void settKey(String tKey) {
        this.tKey = tKey == null ? null : tKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_type.t_des
     *
     * @return the value of movie_type.t_des
     *
     * @mbggenerated
     */
    public String gettDes() {
        return tDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_type.t_des
     *
     * @param tDes the value for movie_type.t_des
     *
     * @mbggenerated
     */
    public void settDes(String tDes) {
        this.tDes = tDes == null ? null : tDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_type.t_title
     *
     * @return the value of movie_type.t_title
     *
     * @mbggenerated
     */
    public String gettTitle() {
        return tTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_type.t_title
     *
     * @param tTitle the value for movie_type.t_title
     *
     * @mbggenerated
     */
    public void settTitle(String tTitle) {
        this.tTitle = tTitle == null ? null : tTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_type.t_union
     *
     * @return the value of movie_type.t_union
     *
     * @mbggenerated
     */
    public String gettUnion() {
        return tUnion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_type.t_union
     *
     * @param tUnion the value for movie_type.t_union
     *
     * @mbggenerated
     */
    public void settUnion(String tUnion) {
        this.tUnion = tUnion == null ? null : tUnion.trim();
    }
}