package cn.generator.pojo;

import java.math.BigDecimal;

public class Movie {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_id
     *
     * @mbggenerated
     */
    private Integer mId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_name
     *
     * @mbggenerated
     */
    private String mName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_subname
     *
     * @mbggenerated
     */
    private String mSubname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_pic
     *
     * @mbggenerated
     */
    private String mPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_picthumb
     *
     * @mbggenerated
     */
    private String mPicthumb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_picslide
     *
     * @mbggenerated
     */
    private String mPicslide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_starring
     *
     * @mbggenerated
     */
    private String mStarring;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_directed
     *
     * @mbggenerated
     */
    private String mDirected;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_tag
     *
     * @mbggenerated
     */
    private String mTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_area
     *
     * @mbggenerated
     */
    private String mArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_lang
     *
     * @mbggenerated
     */
    private String mLang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_year
     *
     * @mbggenerated
     */
    private Short mYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_type
     *
     * @mbggenerated
     */
    private Short mType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_type_expand
     *
     * @mbggenerated
     */
    private String mTypeExpand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_class
     *
     * @mbggenerated
     */
    private String mClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_topic
     *
     * @mbggenerated
     */
    private String mTopic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_hide
     *
     * @mbggenerated
     */
    private Boolean mHide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_lock
     *
     * @mbggenerated
     */
    private Boolean mLock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_state
     *
     * @mbggenerated
     */
    private Integer mState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_level
     *
     * @mbggenerated
     */
    private Integer mLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_hits
     *
     * @mbggenerated
     */
    private Integer mHits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_dayhits
     *
     * @mbggenerated
     */
    private Integer mDayhits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_weekhits
     *
     * @mbggenerated
     */
    private Integer mWeekhits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_monthhits
     *
     * @mbggenerated
     */
    private Integer mMonthhits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_duration
     *
     * @mbggenerated
     */
    private Short mDuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_score
     *
     * @mbggenerated
     */
    private BigDecimal mScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_addtime
     *
     * @mbggenerated
     */
    private Integer mAddtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_time
     *
     * @mbggenerated
     */
    private Integer mTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_playfrom
     *
     * @mbggenerated
     */
    private String mPlayfrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.m_downfrom
     *
     * @mbggenerated
     */
    private String mDownfrom;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_id
     *
     * @return the value of movie.m_id
     *
     * @mbggenerated
     */
    public Integer getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_id
     *
     * @param mId the value for movie.m_id
     *
     * @mbggenerated
     */
    public void setmId(Integer mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_name
     *
     * @return the value of movie.m_name
     *
     * @mbggenerated
     */
    public String getmName() {
        return mName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_name
     *
     * @param mName the value for movie.m_name
     *
     * @mbggenerated
     */
    public void setmName(String mName) {
        this.mName = mName == null ? null : mName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_subname
     *
     * @return the value of movie.m_subname
     *
     * @mbggenerated
     */
    public String getmSubname() {
        return mSubname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_subname
     *
     * @param mSubname the value for movie.m_subname
     *
     * @mbggenerated
     */
    public void setmSubname(String mSubname) {
        this.mSubname = mSubname == null ? null : mSubname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_pic
     *
     * @return the value of movie.m_pic
     *
     * @mbggenerated
     */
    public String getmPic() {
        return mPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_pic
     *
     * @param mPic the value for movie.m_pic
     *
     * @mbggenerated
     */
    public void setmPic(String mPic) {
        this.mPic = mPic == null ? null : mPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_picthumb
     *
     * @return the value of movie.m_picthumb
     *
     * @mbggenerated
     */
    public String getmPicthumb() {
        return mPicthumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_picthumb
     *
     * @param mPicthumb the value for movie.m_picthumb
     *
     * @mbggenerated
     */
    public void setmPicthumb(String mPicthumb) {
        this.mPicthumb = mPicthumb == null ? null : mPicthumb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_picslide
     *
     * @return the value of movie.m_picslide
     *
     * @mbggenerated
     */
    public String getmPicslide() {
        return mPicslide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_picslide
     *
     * @param mPicslide the value for movie.m_picslide
     *
     * @mbggenerated
     */
    public void setmPicslide(String mPicslide) {
        this.mPicslide = mPicslide == null ? null : mPicslide.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_starring
     *
     * @return the value of movie.m_starring
     *
     * @mbggenerated
     */
    public String getmStarring() {
        return mStarring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_starring
     *
     * @param mStarring the value for movie.m_starring
     *
     * @mbggenerated
     */
    public void setmStarring(String mStarring) {
        this.mStarring = mStarring == null ? null : mStarring.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_directed
     *
     * @return the value of movie.m_directed
     *
     * @mbggenerated
     */
    public String getmDirected() {
        return mDirected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_directed
     *
     * @param mDirected the value for movie.m_directed
     *
     * @mbggenerated
     */
    public void setmDirected(String mDirected) {
        this.mDirected = mDirected == null ? null : mDirected.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_tag
     *
     * @return the value of movie.m_tag
     *
     * @mbggenerated
     */
    public String getmTag() {
        return mTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_tag
     *
     * @param mTag the value for movie.m_tag
     *
     * @mbggenerated
     */
    public void setmTag(String mTag) {
        this.mTag = mTag == null ? null : mTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_area
     *
     * @return the value of movie.m_area
     *
     * @mbggenerated
     */
    public String getmArea() {
        return mArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_area
     *
     * @param mArea the value for movie.m_area
     *
     * @mbggenerated
     */
    public void setmArea(String mArea) {
        this.mArea = mArea == null ? null : mArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_lang
     *
     * @return the value of movie.m_lang
     *
     * @mbggenerated
     */
    public String getmLang() {
        return mLang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_lang
     *
     * @param mLang the value for movie.m_lang
     *
     * @mbggenerated
     */
    public void setmLang(String mLang) {
        this.mLang = mLang == null ? null : mLang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_year
     *
     * @return the value of movie.m_year
     *
     * @mbggenerated
     */
    public Short getmYear() {
        return mYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_year
     *
     * @param mYear the value for movie.m_year
     *
     * @mbggenerated
     */
    public void setmYear(Short mYear) {
        this.mYear = mYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_type
     *
     * @return the value of movie.m_type
     *
     * @mbggenerated
     */
    public Short getmType() {
        return mType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_type
     *
     * @param mType the value for movie.m_type
     *
     * @mbggenerated
     */
    public void setmType(Short mType) {
        this.mType = mType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_type_expand
     *
     * @return the value of movie.m_type_expand
     *
     * @mbggenerated
     */
    public String getmTypeExpand() {
        return mTypeExpand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_type_expand
     *
     * @param mTypeExpand the value for movie.m_type_expand
     *
     * @mbggenerated
     */
    public void setmTypeExpand(String mTypeExpand) {
        this.mTypeExpand = mTypeExpand == null ? null : mTypeExpand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_class
     *
     * @return the value of movie.m_class
     *
     * @mbggenerated
     */
    public String getmClass() {
        return mClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_class
     *
     * @param mClass the value for movie.m_class
     *
     * @mbggenerated
     */
    public void setmClass(String mClass) {
        this.mClass = mClass == null ? null : mClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_topic
     *
     * @return the value of movie.m_topic
     *
     * @mbggenerated
     */
    public String getmTopic() {
        return mTopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_topic
     *
     * @param mTopic the value for movie.m_topic
     *
     * @mbggenerated
     */
    public void setmTopic(String mTopic) {
        this.mTopic = mTopic == null ? null : mTopic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_hide
     *
     * @return the value of movie.m_hide
     *
     * @mbggenerated
     */
    public Boolean getmHide() {
        return mHide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_hide
     *
     * @param mHide the value for movie.m_hide
     *
     * @mbggenerated
     */
    public void setmHide(Boolean mHide) {
        this.mHide = mHide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_lock
     *
     * @return the value of movie.m_lock
     *
     * @mbggenerated
     */
    public Boolean getmLock() {
        return mLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_lock
     *
     * @param mLock the value for movie.m_lock
     *
     * @mbggenerated
     */
    public void setmLock(Boolean mLock) {
        this.mLock = mLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_state
     *
     * @return the value of movie.m_state
     *
     * @mbggenerated
     */
    public Integer getmState() {
        return mState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_state
     *
     * @param mState the value for movie.m_state
     *
     * @mbggenerated
     */
    public void setmState(Integer mState) {
        this.mState = mState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_level
     *
     * @return the value of movie.m_level
     *
     * @mbggenerated
     */
    public Integer getmLevel() {
        return mLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_level
     *
     * @param mLevel the value for movie.m_level
     *
     * @mbggenerated
     */
    public void setmLevel(Integer mLevel) {
        this.mLevel = mLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_hits
     *
     * @return the value of movie.m_hits
     *
     * @mbggenerated
     */
    public Integer getmHits() {
        return mHits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_hits
     *
     * @param mHits the value for movie.m_hits
     *
     * @mbggenerated
     */
    public void setmHits(Integer mHits) {
        this.mHits = mHits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_dayhits
     *
     * @return the value of movie.m_dayhits
     *
     * @mbggenerated
     */
    public Integer getmDayhits() {
        return mDayhits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_dayhits
     *
     * @param mDayhits the value for movie.m_dayhits
     *
     * @mbggenerated
     */
    public void setmDayhits(Integer mDayhits) {
        this.mDayhits = mDayhits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_weekhits
     *
     * @return the value of movie.m_weekhits
     *
     * @mbggenerated
     */
    public Integer getmWeekhits() {
        return mWeekhits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_weekhits
     *
     * @param mWeekhits the value for movie.m_weekhits
     *
     * @mbggenerated
     */
    public void setmWeekhits(Integer mWeekhits) {
        this.mWeekhits = mWeekhits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_monthhits
     *
     * @return the value of movie.m_monthhits
     *
     * @mbggenerated
     */
    public Integer getmMonthhits() {
        return mMonthhits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_monthhits
     *
     * @param mMonthhits the value for movie.m_monthhits
     *
     * @mbggenerated
     */
    public void setmMonthhits(Integer mMonthhits) {
        this.mMonthhits = mMonthhits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_duration
     *
     * @return the value of movie.m_duration
     *
     * @mbggenerated
     */
    public Short getmDuration() {
        return mDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_duration
     *
     * @param mDuration the value for movie.m_duration
     *
     * @mbggenerated
     */
    public void setmDuration(Short mDuration) {
        this.mDuration = mDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_score
     *
     * @return the value of movie.m_score
     *
     * @mbggenerated
     */
    public BigDecimal getmScore() {
        return mScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_score
     *
     * @param mScore the value for movie.m_score
     *
     * @mbggenerated
     */
    public void setmScore(BigDecimal mScore) {
        this.mScore = mScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_addtime
     *
     * @return the value of movie.m_addtime
     *
     * @mbggenerated
     */
    public Integer getmAddtime() {
        return mAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_addtime
     *
     * @param mAddtime the value for movie.m_addtime
     *
     * @mbggenerated
     */
    public void setmAddtime(Integer mAddtime) {
        this.mAddtime = mAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_time
     *
     * @return the value of movie.m_time
     *
     * @mbggenerated
     */
    public Integer getmTime() {
        return mTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_time
     *
     * @param mTime the value for movie.m_time
     *
     * @mbggenerated
     */
    public void setmTime(Integer mTime) {
        this.mTime = mTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_playfrom
     *
     * @return the value of movie.m_playfrom
     *
     * @mbggenerated
     */
    public String getmPlayfrom() {
        return mPlayfrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_playfrom
     *
     * @param mPlayfrom the value for movie.m_playfrom
     *
     * @mbggenerated
     */
    public void setmPlayfrom(String mPlayfrom) {
        this.mPlayfrom = mPlayfrom == null ? null : mPlayfrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.m_downfrom
     *
     * @return the value of movie.m_downfrom
     *
     * @mbggenerated
     */
    public String getmDownfrom() {
        return mDownfrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.m_downfrom
     *
     * @param mDownfrom the value for movie.m_downfrom
     *
     * @mbggenerated
     */
    public void setmDownfrom(String mDownfrom) {
        this.mDownfrom = mDownfrom == null ? null : mDownfrom.trim();
    }
}