package cn.generator.pojo;

public class OodManager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_manager.m_id
     *
     * @mbggenerated
     */
    private Short mId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_manager.m_name
     *
     * @mbggenerated
     */
    private String mName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_manager.m_password
     *
     * @mbggenerated
     */
    private String mPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_manager.m_levels
     *
     * @mbggenerated
     */
    private String mLevels;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_manager.m_random
     *
     * @mbggenerated
     */
    private String mRandom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_manager.m_status
     *
     * @mbggenerated
     */
    private Boolean mStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_manager.m_logintime
     *
     * @mbggenerated
     */
    private Integer mLogintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_manager.m_loginip
     *
     * @mbggenerated
     */
    private Integer mLoginip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_manager.m_loginnum
     *
     * @mbggenerated
     */
    private Short mLoginnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ood_manager.m_id
     *
     * @return the value of ood_manager.m_id
     *
     * @mbggenerated
     */
    public Short getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ood_manager.m_id
     *
     * @param mId the value for ood_manager.m_id
     *
     * @mbggenerated
     */
    public void setmId(Short mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ood_manager.m_name
     *
     * @return the value of ood_manager.m_name
     *
     * @mbggenerated
     */
    public String getmName() {
        return mName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ood_manager.m_name
     *
     * @param mName the value for ood_manager.m_name
     *
     * @mbggenerated
     */
    public void setmName(String mName) {
        this.mName = mName == null ? null : mName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ood_manager.m_password
     *
     * @return the value of ood_manager.m_password
     *
     * @mbggenerated
     */
    public String getmPassword() {
        return mPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ood_manager.m_password
     *
     * @param mPassword the value for ood_manager.m_password
     *
     * @mbggenerated
     */
    public void setmPassword(String mPassword) {
        this.mPassword = mPassword == null ? null : mPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ood_manager.m_levels
     *
     * @return the value of ood_manager.m_levels
     *
     * @mbggenerated
     */
    public String getmLevels() {
        return mLevels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ood_manager.m_levels
     *
     * @param mLevels the value for ood_manager.m_levels
     *
     * @mbggenerated
     */
    public void setmLevels(String mLevels) {
        this.mLevels = mLevels == null ? null : mLevels.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ood_manager.m_random
     *
     * @return the value of ood_manager.m_random
     *
     * @mbggenerated
     */
    public String getmRandom() {
        return mRandom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ood_manager.m_random
     *
     * @param mRandom the value for ood_manager.m_random
     *
     * @mbggenerated
     */
    public void setmRandom(String mRandom) {
        this.mRandom = mRandom == null ? null : mRandom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ood_manager.m_status
     *
     * @return the value of ood_manager.m_status
     *
     * @mbggenerated
     */
    public Boolean getmStatus() {
        return mStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ood_manager.m_status
     *
     * @param mStatus the value for ood_manager.m_status
     *
     * @mbggenerated
     */
    public void setmStatus(Boolean mStatus) {
        this.mStatus = mStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ood_manager.m_logintime
     *
     * @return the value of ood_manager.m_logintime
     *
     * @mbggenerated
     */
    public Integer getmLogintime() {
        return mLogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ood_manager.m_logintime
     *
     * @param mLogintime the value for ood_manager.m_logintime
     *
     * @mbggenerated
     */
    public void setmLogintime(Integer mLogintime) {
        this.mLogintime = mLogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ood_manager.m_loginip
     *
     * @return the value of ood_manager.m_loginip
     *
     * @mbggenerated
     */
    public Integer getmLoginip() {
        return mLoginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ood_manager.m_loginip
     *
     * @param mLoginip the value for ood_manager.m_loginip
     *
     * @mbggenerated
     */
    public void setmLoginip(Integer mLoginip) {
        this.mLoginip = mLoginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ood_manager.m_loginnum
     *
     * @return the value of ood_manager.m_loginnum
     *
     * @mbggenerated
     */
    public Short getmLoginnum() {
        return mLoginnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ood_manager.m_loginnum
     *
     * @param mLoginnum the value for ood_manager.m_loginnum
     *
     * @mbggenerated
     */
    public void setmLoginnum(Short mLoginnum) {
        this.mLoginnum = mLoginnum;
    }
}