package cn.generator.pojo;

public class OodUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_id
     *
     * @mbggenerated
     */
    private Integer uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_qid
     *
     * @mbggenerated
     */
    private String uQid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_name
     *
     * @mbggenerated
     */
    private String uName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_password
     *
     * @mbggenerated
     */
    private String uPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_qq
     *
     * @mbggenerated
     */
    private String uQq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_email
     *
     * @mbggenerated
     */
    private String uEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_phone
     *
     * @mbggenerated
     */
    private String uPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_status
     *
     * @mbggenerated
     */
    private Boolean uStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_flag
     *
     * @mbggenerated
     */
    private Boolean uFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_question
     *
     * @mbggenerated
     */
    private String uQuestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_answer
     *
     * @mbggenerated
     */
    private String uAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_group
     *
     * @mbggenerated
     */
    private Short uGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_points
     *
     * @mbggenerated
     */
    private Short uPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_regtime
     *
     * @mbggenerated
     */
    private String uRegtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_logintime
     *
     * @mbggenerated
     */
    private String uLogintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_loginnum
     *
     * @mbggenerated
     */
    private Short uLoginnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_extend
     *
     * @mbggenerated
     */
    private Short uExtend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_loginip
     *
     * @mbggenerated
     */
    private Integer uLoginip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_random
     *
     * @mbggenerated
     */
    private String uRandom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_start
     *
     * @mbggenerated
     */
    private Integer uStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_end
     *
     * @mbggenerated
     */
    private Integer uEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ood_user.u_id
     *
     * @return the value of ood_user.u_id
     *
     * @mbggenerated
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ood_user.u_id
     *
     * @param uId the value for ood_user.u_id
     *
     * @mbggenerated
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ood_user.u_qid
     *
     * @return the value of ood_user.u_qid
     *
     * @mbggenerated
     */
    public String getuQid() {
        return uQid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ood_user.u_qid
     *
     * @param uQid the value for ood_user.u_qid
     *
     * @mbggenerated
     */
    public void setuQid(String uQid) {
        this.uQid = uQid == null ? null : uQid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ood_user.u_name
     *
     * @return the value of ood_user.u_name
     *
     * @mbggenerated
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ood_user.u_name
     *
     * @param uName the value for ood_user.u_name
     *
     * @mbggenerated
     */
    public void setuName(String uName) {
        this.uName = uName == null ? null : uName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ood_user.u_password
     *
     * @return the value of ood_user.u_password
     *
     * @mbggenerated
     */
    public String getuPassword() {
        return uPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ood_user.u_password
     *
     * @param uPassword the value for ood_user.u_password
     *
     * @mbggenerated
     */
    public void setuPassword(String uPassword) {
        this.uPassword = uPassword == null ? null : uPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ood_user.u_qq
     *
     * @return the value of ood_user.u_qq
     *
     * @mbggenerated
     */
    public String getuQq() {
        return uQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ood_user.u_qq
     *
     * @param uQq the value for ood_user.u_qq
     *
     * @mbggenerated
     */
    public void setuQq(String uQq) {
        this.uQq = uQq == null ? null : uQq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ood_user.u_email
     *
     * @return the value of ood_user.u_email
     *
     * @mbggenerated
     */
    public String getuEmail() {
        return uEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ood_user.u_email
     *
     * @param uEmail the value for ood_user.u_email
     *
     * @mbggenerated
     */
    public void setuEmail(String uEmail) {
        this.uEmail = uEmail == null ? null : uEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ood_user.u_phone
     *
     * @return the value of ood_user.u_phone
     *
     * @mbggenerated
     */
    public String getuPhone() {
        return uPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ood_user.u_phone
     *
     * @param uPhone the value for ood_user.u_phone
     *
     * @mbggenerated
     */
    public void setuPhone(String uPhone) {
        this.uPhone = uPhone == null ? null : uPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ood_user.u_status
     *
     * @return the value of ood_user.u_status
     *
     * @mbggenerated
     */
    public Boolean getuStatus() {
        return uStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ood_user.u_status
     *
     * @param uStatus the value for ood_user.u_status
     *
     * @mbggenerated
     */
    public void setuStatus(Boolean uStatus) {
        this.uStatus = uStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ood_user.u_flag
     *
     * @return the value of ood_user.u_flag
     *
     * @mbggenerated
     */
    public Boolean getuFlag() {
        return uFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ood_user.u_flag
     *
     * @param uFlag the value for ood_user.u_flag
     *
     * @mbggenerated
     */
    public void setuFlag(Boolean uFlag) {
        this.uFlag = uFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ood_user.u_question
     *
     * @return the value of ood_user.u_question
     *
     * @mbggenerated
     */
    public String getuQuestion() {
        return uQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ood_user.u_question
     *
     * @param uQuestion the value for ood_user.u_question
     *
     * @mbggenerated
     */
    public void setuQuestion(String uQuestion) {
        this.uQuestion = uQuestion == null ? null : uQuestion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ood_user.u_answer
     *
     * @return the value of ood_user.u_answer
     *
     * @mbggenerated
     */
    public String getuAnswer() {
        return uAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ood_user.u_answer
     *
     * @param uAnswer the value for ood_user.u_answer
     *
     * @mbggenerated
     */
    public void setuAnswer(String uAnswer) {
        this.uAnswer = uAnswer == null ? null : uAnswer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ood_user.u_group
     *
     * @return the value of ood_user.u_group
     *
     * @mbggenerated
     */
    public Short getuGroup() {
        return uGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ood_user.u_group
     *
     * @param uGroup the value for ood_user.u_group
     *
     * @mbggenerated
     */
    public void setuGroup(Short uGroup) {
        this.uGroup = uGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ood_user.u_points
     *
     * @return the value of ood_user.u_points
     *
     * @mbggenerated
     */
    public Short getuPoints() {
        return uPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ood_user.u_points
     *
     * @param uPoints the value for ood_user.u_points
     *
     * @mbggenerated
     */
    public void setuPoints(Short uPoints) {
        this.uPoints = uPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ood_user.u_regtime
     *
     * @return the value of ood_user.u_regtime
     *
     * @mbggenerated
     */
    public String getuRegtime() {
        return uRegtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ood_user.u_regtime
     *
     * @param uRegtime the value for ood_user.u_regtime
     *
     * @mbggenerated
     */
    public void setuRegtime(String uRegtime) {
        this.uRegtime = uRegtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ood_user.u_logintime
     *
     * @return the value of ood_user.u_logintime
     *
     * @mbggenerated
     */
    public String getuLogintime() {
        return uLogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ood_user.u_logintime
     *
     * @param uLogintime the value for ood_user.u_logintime
     *
     * @mbggenerated
     */
    public void setuLogintime(String uLogintime) {
        this.uLogintime = uLogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ood_user.u_loginnum
     *
     * @return the value of ood_user.u_loginnum
     *
     * @mbggenerated
     */
    public Short getuLoginnum() {
        return uLoginnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ood_user.u_loginnum
     *
     * @param uLoginnum the value for ood_user.u_loginnum
     *
     * @mbggenerated
     */
    public void setuLoginnum(Short uLoginnum) {
        this.uLoginnum = uLoginnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ood_user.u_extend
     *
     * @return the value of ood_user.u_extend
     *
     * @mbggenerated
     */
    public Short getuExtend() {
        return uExtend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ood_user.u_extend
     *
     * @param uExtend the value for ood_user.u_extend
     *
     * @mbggenerated
     */
    public void setuExtend(Short uExtend) {
        this.uExtend = uExtend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ood_user.u_loginip
     *
     * @return the value of ood_user.u_loginip
     *
     * @mbggenerated
     */
    public Integer getuLoginip() {
        return uLoginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ood_user.u_loginip
     *
     * @param uLoginip the value for ood_user.u_loginip
     *
     * @mbggenerated
     */
    public void setuLoginip(Integer uLoginip) {
        this.uLoginip = uLoginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ood_user.u_random
     *
     * @return the value of ood_user.u_random
     *
     * @mbggenerated
     */
    public String getuRandom() {
        return uRandom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ood_user.u_random
     *
     * @param uRandom the value for ood_user.u_random
     *
     * @mbggenerated
     */
    public void setuRandom(String uRandom) {
        this.uRandom = uRandom == null ? null : uRandom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ood_user.u_start
     *
     * @return the value of ood_user.u_start
     *
     * @mbggenerated
     */
    public Integer getuStart() {
        return uStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ood_user.u_start
     *
     * @param uStart the value for ood_user.u_start
     *
     * @mbggenerated
     */
    public void setuStart(Integer uStart) {
        this.uStart = uStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ood_user.u_end
     *
     * @return the value of ood_user.u_end
     *
     * @mbggenerated
     */
    public Integer getuEnd() {
        return uEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ood_user.u_end
     *
     * @param uEnd the value for ood_user.u_end
     *
     * @mbggenerated
     */
    public void setuEnd(Integer uEnd) {
        this.uEnd = uEnd;
    }
}