package cn.generator.pojo;

public class OodUserWithBLOBs extends OodUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_fav
     *
     * @mbggenerated
     */
    private String uFav;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_plays
     *
     * @mbggenerated
     */
    private String uPlays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_downs
     *
     * @mbggenerated
     */
    private String uDowns;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ood_user.u_fav
     *
     * @return the value of ood_user.u_fav
     *
     * @mbggenerated
     */
    public String getuFav() {
        return uFav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ood_user.u_fav
     *
     * @param uFav the value for ood_user.u_fav
     *
     * @mbggenerated
     */
    public void setuFav(String uFav) {
        this.uFav = uFav == null ? null : uFav.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ood_user.u_plays
     *
     * @return the value of ood_user.u_plays
     *
     * @mbggenerated
     */
    public String getuPlays() {
        return uPlays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ood_user.u_plays
     *
     * @param uPlays the value for ood_user.u_plays
     *
     * @mbggenerated
     */
    public void setuPlays(String uPlays) {
        this.uPlays = uPlays == null ? null : uPlays.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ood_user.u_downs
     *
     * @return the value of ood_user.u_downs
     *
     * @mbggenerated
     */
    public String getuDowns() {
        return uDowns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ood_user.u_downs
     *
     * @param uDowns the value for ood_user.u_downs
     *
     * @mbggenerated
     */
    public void setuDowns(String uDowns) {
        this.uDowns = uDowns == null ? null : uDowns.trim();
    }
}