package cn.generator.pojo;

/**
 * Created by vog1g on 2017/5/19.
 */
public class UserWithRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_role.r_id
     *
     * @mbggenerated
     */
    private Integer rId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_role.r_name
     *
     * @mbggenerated
     */
    private String rName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_role.r_addtime
     *
     * @mbggenerated
     */
    private String rAddtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_role.r_type
     *
     * @mbggenerated
     */
    private Integer rType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_role.r_power
     *
     * @mbggenerated
     */
    private String rPower;

    private Integer uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_qid
     *
     * @mbggenerated
     */
    private String uQid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_name
     *
     * @mbggenerated
     */
    private String uName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_password
     *
     * @mbggenerated
     */
    private String uPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_qq
     *
     * @mbggenerated
     */
    private String uQq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_email
     *
     * @mbggenerated
     */
    private String uEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_phone
     *
     * @mbggenerated
     */
    private String uPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_status
     *
     * @mbggenerated
     */
    private Boolean uStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_flag
     *
     * @mbggenerated
     */
    private Boolean uFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_question
     *
     * @mbggenerated
     */
    private String uQuestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_answer
     *
     * @mbggenerated
     */
    private String uAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_group
     *
     * @mbggenerated
     */
    private Short uGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_points
     *
     * @mbggenerated
     */
    private Short uPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_regtime
     *
     * @mbggenerated
     */
    private String uRegtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_logintime
     *
     * @mbggenerated
     */
    private String uLogintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_loginnum
     *
     * @mbggenerated
     */
    private Short uLoginnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_extend
     *
     * @mbggenerated
     */
    private Short uExtend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_loginip
     *
     * @mbggenerated
     */
    private Integer uLoginip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_random
     *
     * @mbggenerated
     */
    private String uRandom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_start
     *
     * @mbggenerated
     */
    private Integer uStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ood_user.u_end
     *
     * @mbggenerated
     */
    private Integer uEnd;

    public Integer getrId() {
        return rId;
    }

    public void setrId(Integer rId) {
        this.rId = rId;
    }

    public String getrName() {
        return rName;
    }

    public void setrName(String rName) {
        this.rName = rName;
    }

    public String getrAddtime() {
        return rAddtime;
    }

    public void setrAddtime(String rAddtime) {
        this.rAddtime = rAddtime;
    }

    public Integer getrType() {
        return rType;
    }

    public void setrType(Integer rType) {
        this.rType = rType;
    }

    public String getrPower() {
        return rPower;
    }

    public void setrPower(String rPower) {
        this.rPower = rPower;
    }

    public Integer getuId() {
        return uId;
    }

    public void setuId(Integer uId) {
        this.uId = uId;
    }

    public String getuQid() {
        return uQid;
    }

    public void setuQid(String uQid) {
        this.uQid = uQid;
    }

    public String getuName() {
        return uName;
    }

    public void setuName(String uName) {
        this.uName = uName;
    }

    public String getuPassword() {
        return uPassword;
    }

    public void setuPassword(String uPassword) {
        this.uPassword = uPassword;
    }

    public String getuQq() {
        return uQq;
    }

    public void setuQq(String uQq) {
        this.uQq = uQq;
    }

    public String getuEmail() {
        return uEmail;
    }

    public void setuEmail(String uEmail) {
        this.uEmail = uEmail;
    }

    public String getuPhone() {
        return uPhone;
    }

    public void setuPhone(String uPhone) {
        this.uPhone = uPhone;
    }

    public Boolean getuStatus() {
        return uStatus;
    }

    public void setuStatus(Boolean uStatus) {
        this.uStatus = uStatus;
    }

    public Boolean getuFlag() {
        return uFlag;
    }

    public void setuFlag(Boolean uFlag) {
        this.uFlag = uFlag;
    }

    public String getuQuestion() {
        return uQuestion;
    }

    public void setuQuestion(String uQuestion) {
        this.uQuestion = uQuestion;
    }

    public String getuAnswer() {
        return uAnswer;
    }

    public void setuAnswer(String uAnswer) {
        this.uAnswer = uAnswer;
    }

    public Short getuGroup() {
        return uGroup;
    }

    public void setuGroup(Short uGroup) {
        this.uGroup = uGroup;
    }

    public Short getuPoints() {
        return uPoints;
    }

    public void setuPoints(Short uPoints) {
        this.uPoints = uPoints;
    }

    public String getuRegtime() {
        return uRegtime;
    }

    public void setuRegtime(String uRegtime) {
        this.uRegtime = uRegtime;
    }

    public String getuLogintime() {
        return uLogintime;
    }

    public void setuLogintime(String uLogintime) {
        this.uLogintime = uLogintime;
    }

    public Short getuLoginnum() {
        return uLoginnum;
    }

    public void setuLoginnum(Short uLoginnum) {
        this.uLoginnum = uLoginnum;
    }

    public Short getuExtend() {
        return uExtend;
    }

    public void setuExtend(Short uExtend) {
        this.uExtend = uExtend;
    }

    public Integer getuLoginip() {
        return uLoginip;
    }

    public void setuLoginip(Integer uLoginip) {
        this.uLoginip = uLoginip;
    }

    public String getuRandom() {
        return uRandom;
    }

    public void setuRandom(String uRandom) {
        this.uRandom = uRandom;
    }

    public Integer getuStart() {
        return uStart;
    }

    public void setuStart(Integer uStart) {
        this.uStart = uStart;
    }

    public Integer getuEnd() {
        return uEnd;
    }

    public void setuEnd(Integer uEnd) {
        this.uEnd = uEnd;
    }
}
